name: Run App with Docker

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest  # Fix typo here: changed 'upuntu-latest' to 'ubuntu-latest'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          echo "--------- start ----------"
          docker build -t express .
      
      - name: Run Docker container
        run: |
          docker run -p 3000:3000 --name express express
      
